### ISSUE TITLE
Footer message on upload page

### ISSUE THREAD

**Issue by stevieflow** [notshi/d-preview#10]
Change from 

> For preview purposes only. Data will not be uploaded to the main live d-portal website.
> Project page, issues and feedback on Github.

to

> For preview purposes only. Data will not be uploaded to the main live d-portal website.
> This is a community hosted service.  All preview instances will auto-delete after seven days.
> Project page, issues and feedback on Github.

**Comment by stevieflow** [comment]
Also - can we link to the blog announcement (when we publish it)?

**Comment by notshi** [comment]
Sure, just let me know the url and I'll add it in.

**Comment by notshi** [comment]
The text has been changed and is now live.

**Comment by stevieflow** [comment]
> The text has been changed and is now live.

I cant see that on http://d-preview.codeforiati.org/upload ...

**Comment by notshi** [comment]
Ahh yes, it's on the live main pages and in local changes but not the live upload page yet.
Would you be able to provide a blog post link today?

Am hoping to check in all the changes to go live at the same time.

**Comment by notshi** [comment]
Footer message on upload page has been updated and is now live. Will update with a blog link when that's live.

**Comment by stevieflow** [comment]
blog post: https://medium.com/opendatacoop/announcing-d-preview-helping-organisations-check-their-iati-data-before-publishing-669b24ae20d

**Comment by notshi** [comment]
Blog post link is now live on the site.

**Comment by notshi** [comment]
> Did we also want to add that link to the blog to the generated preview sites?

As in, add a link to the blog post in the footer of generated preview sites?

**Comment by stevieflow** [comment]
> As in, add a link to the blog post in the footer of generated preview sites?

Yes please

**Comment by notshi** [comment]
Should be live now.
