### ISSUE TITLE
Button / link to create a new preview (from a preview)

### ISSUE THREAD

**Issue by stevieflow** [notshi/d-preview#18]
A useful thing would be to have a button or link to take you to the upload page, from any preview page.

**Comment by notshi** [comment]
The blue d-preview link in the footer should lead you to the upload page (not live yet) but we've also added a create preview button.
![Screenshot-20210301104011-905x371](https://user-images.githubusercontent.com/1515961/109486252-87549c00-7a7a-11eb-9ccb-9f5eddbb0ccb.png)

Hoping to check in the changes with https://github.com/notshi/d-preview/issues/10#issuecomment-787839191

**Comment by notshi** [comment]
Both link and button are now live.
