### ISSUE TITLE
Provide an example preview

### ISSUE THREAD

**Issue by stevieflow** [notshi/d-preview#19]
It would be helpful to provide users with a link to an example preview - just in case they havent any XML to hand!

With CoVE we maintain an example file: 

https://docs.google.com/spreadsheets/d/1V8Cs4rivr6HDiDsne2bVECJiAXHcHBDiy_JEU9oPgRQ/edit?usp=sharing

This converts to IATI XML:

https://iati.cove.opendataservices.coop/?source_url=https://docs.google.com/spreadsheets/d/1V8Cs4rivr6HDiDsne2bVECJiAXHcHBDiy_JEU9oPgRQ/export?format=xlsx

Obviously, the CoVE XML will expire, and so too would a d-preview.  Could we hardwire something, somehow?

Suggested text 
==========

Haven't got any IATI XML to hand?  Try our example activity here..

**Comment by xriss** [comment]
There is a root site, http://d-preview.codeforiati.org/ctrack.html#view=main which is currently populated with an old data dump of all of iati.

Can switch this over to whatever example file you want, just need to decide on the file.

Maybe, only having one activity, as in your example file, is not a good full example?

**Comment by stevieflow** [comment]
Thanks @xriss 

For now, could we switch to https://github.com/OpenDataServices/iati-sample-data/blob/master/IATI-CoVE-sample-activity-standard.xml ?

Agree with you that a single activity might not be best.  We can try and mint more comprehensive examples via something like https://github.com/codeforIATI/iati-ideas/issues/18

**Comment by notshi** [comment]
@stevieflow This is now live on the website. Do let us know if you want an alternative url.
