### ISSUE TITLE
Getting errors loading data?

### ISSUE THREAD

**Issue by notshi** [notshi/d-preview#20]
Via [Twitter](https://twitter.com/__siem__/status/1367420053763801088):
![Screenshot-20210304140222-595x540](https://user-images.githubusercontent.com/1515961/109975171-45ce2600-7cf2-11eb-8ab8-9ededcb8c149.png)

**Comment by notshi** [comment]
This looks like a fundamental network connection issue as you are not even connecting to our NGINX.

Can you try again with a different browser and a different location as it doesn't seem to be an error at our end and we have limited information to work on from what you have provided.

Do you have any add-ons or extensions on the browser you are using that might be interfering?

**Comment by stevieflow** [comment]
@siemvaessen ^^

**Comment by siemvaessen** [comment]
Probably a tired Chrome session. Tested in Canary and could not reproduce. Do close.

**Comment by stevieflow** [comment]
@siemvaessen thanks.  Chrome gets so tired, so often :(
