### ISSUE TITLE
Uncaught TypeError: Cannot read property 'count_aid' of undefined

### ISSUE THREAD

**Issue by siemvaessen** [notshi/d-preview#21]
![Screenshot 2021-03-04 at 15 49 26](https://user-images.githubusercontent.com/961036/109981476-3dc9b280-7d01-11eb-909f-62c0e42880c0.png)

Adding XML on URI - works in the end, did notice Uncaught TypeError: 

Chrome Canary

**Comment by stevieflow** [comment]
Thanks @siemvaessen 

Any chance to share the URI of the XML you were trying to preview?  Was this "standard" IATI XML, or did it have additional fields (called ``count_aid``?)?

**Comment by siemvaessen** [comment]
Hmm, dropped all my test files last week, so not sure anymore. I will close it as I am unable to reproduce this with another set 'from the Metadata Registry' now.
