### ISSUE TITLE
auto-delete not deleting

### ISSUE THREAD

**Issue by stevieflow** [notshi/d-preview#24]
I've observed that d-previews I created some time ago are still there, so I dont believe the auto-delete function is in place

Is this the case @notshi @xriss 

As we advertise this, it's probably best to get this going !

**Comment by notshi** [comment]
Thanks, @stevieflow - the code is now in place.

We are now testing and observing the logs so it will be a couple of days before this goes live.

**Comment by notshi** [comment]
This is now live but do let us know otherwise!
