### ISSUE TITLE
Indicator periods missing

### ISSUE THREAD

**Issue by IsabelBirds** [notshi/d-preview#29]
Hi!

I'm having an issue with indicator periods, where the period is in the xml, but marked as not provided on d-preview. I can't see anything obvious wrong with the xml, and the indicator period is within the activity start and end dates. This has occurred for multiple indicators and results, always on the last indicator period. 

A basic example which includes this error is attached, and [previewed.](http://e5cda5103655b18ea87b2dbf343100f3.d-preview.codeforiati.org/ctrack.html#view=act&aid=CH-FDJP-CHE109994012-60056)

[test_result.xml.zip](https://github.com/notshi/d-preview/files/11770994/test_result.xml.zip)

![image](https://github.com/notshi/d-preview/assets/44876111/cc5a494d-7ecc-46a8-9cd8-ad61c6d67264)

Thanks for your help :)

**Comment by notshi** [comment]
Many thanks for raising this.

There was a check that meant periods for results with future dates were not being displayed.
A fix has been pushed and it should be live tomorrow after the nightly updates.

However, do let me know if that is not the case for you.

**Comment by notshi** [comment]
![Screenshot_20230625_150528](https://github.com/notshi/d-preview/assets/1515961/32561c83-ca52-4d88-b3a7-45c118a66c0d)

Hopefully this is what you expected.
Do let me know if you are still having issues.

**Comment by IsabelBirds** [comment]
That's fab, thank you! 
Sorry for the slow response! :)
