### ISSUE TITLE
Google Maps broken on preview page

### ISSUE THREAD

**Issue by odscjames** [notshi/d-preview#30]
"Google Maps JavaScript API error: RefererNotAllowedMapError"

**Comment by notshi** [comment]
Thanks for raising, @odscjames - could we confirm that the d-preview map key is restricted to the following domains?

```
https://d-preview.codeforiati.org
https://*.d-preview.codeforiati.org
https://d-preview.codeforiati.org/*

http://d-preview.codeforiati.org
http://*.d-preview.codeforiati.org
http://d-preview.codeforiati.org/*
```

**Comment by odscjames** [comment]
Nope, those aren't included - I'll add them now

**Comment by odscjames** [comment]
I don't think we ever provided you with a key for D-Preview, just D-portal. You want one with those referrers?

I've just looked and I can't see the key  D-preview is currently using in our system

**Comment by odscjames** [comment]
[ Sorry, ignore deleted messages - Google Cloud UI tripping me up! ]

No, it wasn't allowed on subdomains - I'll add now

**Comment by odscjames** [comment]
Working now
