### ISSUE TITLE
IATI identifier is a link to the live site

### ISSUE THREAD

**Issue by stevieflow** [notshi/d-preview#5]
On preview sites, the IATI identifier is still a link

![d-portal (45)](https://user-images.githubusercontent.com/1209944/107801249-bf0fd400-6d57-11eb-92b8-b302717d99bc.png)

but  this is a link to the live d-portal, and so would not work in many previews.  When it does work in previews, it would also be confusing to the user.

I would recommend that this is just printed on screen, without being a link

(NB: this function is very useful on live d-portal btw!)

**Comment by xriss** [comment]
All links should now stay inside the instanced site rather than link out to the live site.

So will either work as expected within the current uploaded data or fail, this should also deal with #4 and #6

I think this is everywhere but let me know if you find a link that escapes from the sandbox.

**Comment by stevieflow** [comment]
Thanks @xriss 

I noticed that the link to the Data Logs and IATI Registry are changed, but in either case - would not work in the preview.  Ill update the #4
