### ISSUE TITLE
Links to other activities and organisations in the preview site

### ISSUE THREAD

**Issue by stevieflow** [notshi/d-preview#6]
When submitted IATI data contains an org/@ref or activity-identifier then this creates a link to the relevant page on live d-portal.

This is useful functionality on live d-portal (although some issues discussed in https://github.com/devinit/D-Portal/issues/602), but could be confusing in the preview environment

The links do open in a new tab, so that negates issues slightly.  I'd suggest this is lower priority to remedy

**Comment by notshi** [comment]
https://github.com/notshi/d-preview/issues/5#issuecomment-779098900
