### ISSUE TITLE
Submit data to preview interface via URL

### ISSUE THREAD

**Issue by stevieflow** [notshi/d-preview#7]
With @markbrough & @andylolz we noticed that whilst we can construct d-portal previews via URL , these are not encoded

Example - Datastore Classic query: https://datastore.codeforiati.org/api/1/access/activity.xml?reporting-org=44000&recipient-country=LR

- This preview http://portald.wetgenes.com/upload?xmlurl=https://datastore.codeforiati.org/api/1/access/activity.xml?reporting-org=44000&recipient-country=LR doesnt parse this file correctly (there are activities outside of LR): 

http://ed1223157812cf733764ff4847d8c038.portald.wetgenes.com/ctrack.html#view=main

whereas

- http://portald.wetgenes.com/upload?xmlurl=https%3A%2F%2Fdatastore.codeforiati.org%2Fapi%2F1%2Faccess%2Factivity.xml%3Freporting-org%3D44000%26recipient-country%3DLR

encodes the URL and therefore previews the data in the query

http://cecc6a315bb0e41c2db46f5729518d49.portald.wetgenes.com/ctrack.html#view=main

Could the interface to the preview support URL submission, in the same way we have via CoVE (for example): https://iati.cove.opendataservices.coop/

I'm not exactly sure how this differs from what is setup with @bjwebb already btw - one to discuss

Thanks

**Comment by notshi** [comment]
Hi @stevieflow there is now an interface to submit a url.
