### ISSUE TITLE
Add stats

### ISSUE THREAD

**Issue by stevieflow** [notshi/d-preview#9]
Add a page to monitor usage - like: https://iati.cove.opendataservices.coop/stats/

Importantly, this should NOT provide any access to the underlying previews

**Comment by notshi** [comment]
Hi, @stevieflow just letting you know we are currently working on this and it will take a few days.

**Comment by notshi** [comment]
There should be some stats here now https://notshi.github.io/d-preview/

**Comment by stevieflow** [comment]
Really interesting - thanks!

I'm guessing these will continue to accumulate, over time - and then segment by month, or something (shall we just watch this space..?)

Also - would we want / be able to put these at d-preview.codeforiati.org/stats ..?

**Comment by notshi** [comment]
Have added nightly stats similar to the table for CoVE.

**Comment by stevieflow** [comment]
@notshi - thanks

Would it be possible to put a link to the stats https://notshi.github.io/d-preview/ from the d-preview "homepage"?  That way, I wont have to navigate back to this ticket each time ;)

**Comment by notshi** [comment]
Yes, of course! The link should now be on the homepage.
